const THEMES={
"Back to School":{icon:"🎒✏️",words:["PENCIL","BOOK","DESK","CLASS","TEACHER","SCHOOL","CRAYON","PAPER","RULER","GLUE","ERASER","CHAIR","READ","WRITE","MATH","LEARN","LUNCH","RECESS","FRIEND","FOLDER","MARKER","SCISSORS","BACKPACK","LIBRARY","STUDENT","COMPUTER","NOTEBOOK","CALENDAR","PROJECT","SCIENCE"]},
"Fall":{icon:"🍂🍎",words:["APPLE","ACORN","LEAF","AUTUMN","CIDER","PUMPKIN","HARVEST","CORN","HAY","SCARECROW","ORANGE","BROWN","CRISP","BREEZE","MAPLE","OAK","RAKE","PIE","ORCHARD","SQUIRREL","CHESTNUT","SWEATER","JACKET","BONFIRE","FARM","WAGON","SUNFLOWER","CINNAMON","FOOTBALL","SEPTEMBER"]},
"Halloween":{icon:"🎃👻",words:["GHOST","WITCH","BAT","CANDY","SPOOKY","MASK","TRICK","TREAT","SPIDER","WEB","BLACK","CAT","MOON","BROOM","POTION","MONSTER","MUMMY","SKULL","BONES","HAUNTED","COSTUME","VAMPIRE","ZOMBIE","CACKLE","CAULDRON","LANTERN","PUMPKIN","SHADOW","SCREAM","OCTOBER"]},
"Thanksgiving":{icon:"🦃🥧",words:["TURKEY","THANKS","FEAST","PIE","CORN","GRAVY","FAMILY","DINNER","HARVEST","ROLLS","YAM","APPLE","PUMPKIN","PLATE","FORK","TABLE","AUTUMN","LEAVES","PARADE","NOVEMBER","GATHER","SHARE","KINDNESS","GRATEFUL","CRANBERRY","STUFFING","POTATO","CARROT","TRADITION","CELEBRATE"]},
"Christmas":{icon:"🎄🎁",words:["SANTA","ELF","TREE","GIFT","STAR","BELLS","SNOW","SLEIGH","HOLLY","LIGHTS","CAROL","JOY","MERRY","COOKIE","REINDEER","RUDOLPH","STOCKING","ORNAMENT","WREATH","CANDY","COCOA","CHIMNEY","TINSEL","ANGEL","NORTH","POLE","DECEMBER","PRESENT","FAMILY","CHEER"]},
"Winter":{icon:"❄️⛄",words:["SNOW","COLD","ICE","FROST","MITTEN","SCARF","COAT","BOOTS","SLED","SKATE","SKI","FLAKE","WINTER","CHILLY","COCOA","IGLOO","PENGUIN","POLAR","STORM","FREEZE","ICICLE","SNOWMAN","BLIZZARD","JACKET","HAT","FIREPLACE","JANUARY","FEBRUARY","WHITE","CRYSTAL"]},
"Valentine":{icon:"💗💌",words:["LOVE","HEART","CARD","PINK","RED","CANDY","HUG","KIND","FRIEND","ROSE","CUPID","SWEET","SMILE","HAPPY","CHOCOLATE","FLOWER","LETTER","CARING","SHARE","KISS","FEBRUARY","BE MINE","ADORABLE","FRIENDSHIP","HEARTS","GIFT","CUTE","JOY","SPECIAL","VALENTINE"]},
"St. Patrick":{icon:"☘️🌈",words:["GREEN","CLOVER","LUCK","RAINBOW","GOLD","IRISH","HAT","COIN","MARCH","SHAMROCK","LEPRECHAUN","POT","DANCE","JIG","MAGIC","CHARM","PARADE","SPRING","EMERALD","CELTIC","IRELAND","LUCKY","FIDDLE","BAGPIPE","GREENERY","TREASURE","TRADITION","CELEBRATE","SAINT","PATRICK"]},
"Spring":{icon:"🌷🐝",words:["SPRING","FLOWER","RAIN","BEE","BIRD","NEST","BLOOM","GARDEN","TULIP","DAISY","GREEN","GRASS","SUN","WARM","CLOUD","PUDDLE","RAINBOW","BUTTERFLY","CATERPILLAR","SEED","PLANT","BUD","ROBIN","BUNNY","APRIL","MAY","PICNIC","BREEZE","GROW","NATURE"]},
"Summer":{icon:"☀️🍉",words:["SUMMER","SUN","BEACH","POOL","SWIM","SAND","SHELL","WAVE","OCEAN","SUNNY","PICNIC","CAMP","MELON","LEMONADE","ICE CREAM","SHORTS","HAT","SURF","BOAT","FISH","JUNE","JULY","AUGUST","VACATION","TRAVEL","PARK","PLAY","HOT","WATER","SUNSET"]}
};
// Spaces are removed in gameplay, so BE MINE and ICE CREAM become BEMINE / ICECREAM.

const EXTRA_WORDS = `ABOUT ABOVE ACTOR ACUTE ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT ALIKE ALIVE ALLOW ALONE ALONG ALTER AMONG ANGER ANGLE ANGRY APART APPLE APPLY ARGUE ARISE ARRAY ASIDE AUDIO AVOID AWARD AWARE BADLY BAKER BASES BASIC BASIS BEACH BEGAN BEGIN BEGUN BEING BELOW BENCH BILLY BIRTH BLACK BLAME BLIND BLOCK BLOOD BOARD BOOST BOOTH BOUND BRAIN BRAND BREAD BREAK BREED BRIEF BRING BROAD BROKE BROWN BUILD BUILT BUYER CABLE CALIF CARRY CATCH CAUSE CHAIN CHAIR CHART CHASE CHEAP CHECK CHEST CHIEF CHILD CHINA CHOSE CIVIL CLAIM CLASS CLEAN CLEAR CLICK CLOCK CLOSE COACH COAST COULD COUNT COURT COVER CRAFT CRASH CREAM CRIME CROSS CROWD CROWN CURVE CYCLE DAILY DANCE DATED DEALT DEATH DEBUT DELAY DEPTH DOING DOUBT DOZEN DRAFT DRAMA DRAWN DREAM DRESS DRILL DRINK DRIVE DROVE DYING EAGER EARLY EARTH EIGHT ELITE EMPTY ENEMY ENJOY ENTER ENTRY EQUAL ERROR EVENT EVERY EXACT EXIST EXTRA FAITH FALSE FAULT FIBER FIELD FIFTH FIFTY FIGHT FINAL FIRST FIXED FLASH FLEET FLOOR FLUID FOCUS FORCE FORTH FORTY FORUM FOUND FRAME FRANK FRAUD FRESH FRONT FRUIT FULLY FUNNY GIANT GIVEN GLASS GLOBE GOING GRACE GRADE GRAND GRANT GRASS GREAT GREEN GROSS GROUP GROWN GUARD GUESS GUEST GUIDE HAPPY HEART HEAVY HENCE HENRY HORSE HOTEL HOUSE HUMAN IDEAL IMAGE INDEX INNER INPUT ISSUE JAPAN JIMMY JOINT JONES JUDGE KNOWN LABEL LARGE LASER LATER LAUGH LAYER LEARN LEAST LEAVE LEGAL LEVEL LEWIS LIGHT LIMIT LINKS LIVES LOCAL LOGIC LOOSE LOWER LUCKY LUNCH LYING MAGIC MAJOR MAKER MARCH MARIA MATCH MAYBE MAYOR MEANT MEDIA METAL MIGHT MINOR MINUS MIXED MODEL MONEY MONTH MORAL MOTOR MOUNT MOUSE MOUTH MOVIE MUSIC NEEDS NEVER NEWLY NIGHT NOISE NORTH NOTED NOVEL NURSE OCCUR OCEAN OFFER OFTEN ORDER OTHER OUGHT PAINT PANEL PAPER PARTY PEACE PETER PHASE PHONE PHOTO PIECE PILOT PITCH PLACE PLAIN PLANE PLANT PLATE POINT POUND POWER PRESS PRICE PRIDE PRIME PRINT PRIOR PRIZE PROOF PROUD QUEEN QUICK QUIET QUITE RADIO RAISE RANGE RAPID RATIO REACH READY REFER RIGHT RIVAL RIVER ROBIN ROGER ROMAN ROUGH ROUND ROUTE ROYAL RURAL SCALE SCENE SCOPE SCORE SENSE SERVE SEVEN SHALL SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT SHIRT SHOCK SHOOT SHORT SHOWN SIGHT SINCE SIXTH SIXTY SIZED SKILL SLEEP SLIDE SMALL SMART SMILE SMITH SMOKE SOLID SOLVE SORRY SOUND SOUTH SPACE SPARE SPEAK SPEED SPEND SPENT SPLIT SPOKE SPORT STAFF STAGE STAKE STAND START STATE STEAM STEEL STICK STILL STOCK STONE STOOD STORE STORM STORY STRIP STUCK STUDY STUFF STYLE SUGAR SUITE SUPER SWEET TABLE TAKEN TASTE TAXES TEACH TEETH TERRY TEXAS THANK THEIR THEME THERE THESE THICK THING THINK THIRD THOSE THREE THREW THROW TIGHT TIMES TIRED TITLE TODAY TOPIC TOTAL TOUCH TOUGH TOWER TRACK TRADE TRAIN TREAT TREND TRIAL TRIED TRIES TRUCK TRULY TRUST TRUTH TWICE UNDER UNDUE UNION UNITY UNTIL UPPER UPSET URBAN USAGE USUAL VALID VALUE VIDEO VIRUS VISIT VITAL VOICE WASTE WATCH WATER WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WOMAN WOMEN WORLD WORRY WORSE WORST WORTH WOULD WOUND WRITE WRONG WROTE YIELD YOUNG YOUTH`.split(/\s+/);
const clean=s=>s.toUpperCase().replace(/[^A-Z]/g,'');
const VALID_WORDS=new Set([...Object.values(THEMES).flatMap(t=>t.words.map(clean)),...EXTRA_WORDS.map(clean)]);

const app=document.querySelector('#app'); let state={theme:null,index:0,answer:'',guess:'',row:0,max:6,board:[],status:'playing',custom:false,key:{}};
function shell(inner){app.innerHTML=`<div class="wrap"><header class="brand"><img src="logo.png" alt="Hug & Grow Learning Studio logo" class="brand-logo"><div><h1>Hug & Grow Wordle</h1><p>Build words, grow confidence, have fun!</p></div></header>${inner}<div class="footer">© 2026 Hug & Grow Learning Studio. All rights reserved.</div></div>`}
function home(){let buttons=Object.entries(THEMES).map(([n,t])=>`<button class="theme" data-theme="${n}"><div class="decor">${t.icon}</div>${n}</button>`).join('');shell(`<section class="card"><h2>Choose a Wordle Theme</h2><p class="hint">Each seasonal theme includes 30 games. Word length changes automatically.</p><div class="themes">${buttons}<button class="theme" id="custom"><div class="decor">✍️✨</div>Customize</button></div></section>`);document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>picker(b.dataset.theme));document.querySelector('#custom').onclick=customSetup}
function picker(theme){const t=THEMES[theme];shell(`<section class="card"><div class="top"><button class="pill" id="back">← Themes</button><h2>${t.icon} ${theme}</h2></div><p>Choose a game:</p><div class="game-picker">${t.words.map((_,i)=>`<button data-i="${i}">${i+1}</button>`).join('')}</div></section>`);document.querySelector('#back').onclick=home;document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>start(theme,+b.dataset.i))}
function start(theme,index){state={theme,index,answer:clean(THEMES[theme].words[index]),guess:'',row:0,max:6,board:[],status:'playing',custom:false,key:{}};renderGame()}
function customSetup(){shell(`<section class="card modal"><div class="top"><button class="pill" id="back">← Themes</button><h2>✍️ Teacher Customize</h2></div><p>Type the secret answer. Letters only; spaces and punctuation are ignored during play.</p><input class="field" id="answer" maxlength="12" placeholder="Secret word" autocomplete="off"><p class="hint">Recommended: 3–12 letters. After you press Start, the word will disappear.</p><button class="action" id="go">Start Student Game</button></section>`);document.querySelector('#back').onclick=home;document.querySelector('#go').onclick=()=>{let a=clean(document.querySelector('#answer').value);if(a.length<2)return alert('Please enter at least 2 letters.');state={theme:'Customize',index:0,answer:a,guess:'',row:0,max:6,board:[],status:'playing',custom:true,key:{}};renderGame()}}
function renderGame(){const len=state.answer.length;let rows='';for(let r=0;r<state.max;r++){let chars=state.board[r]?.letters||(r===state.row?state.guess:'');let res=state.board[r]?.result||[];rows+=`<div class="row" style="grid-template-columns:repeat(${len},minmax(0,58px))">${Array.from({length:len},(_,i)=>`<div class="tile ${res[i]||''}">${chars[i]||''}</div>`).join('')}</div>`}let title=state.custom?'✍️ Custom Wordle':`${THEMES[state.theme].icon} ${state.theme}`;let progress=state.custom?'Teacher-created game':`Game ${state.index+1} of 30`;shell(`<section class="card"><div class="top"><button class="pill" id="back">← ${state.custom?'Themes':'Games'}</button><div><strong>${title}</strong><div class="hint">${progress} • ${len} letters</div></div><button class="pill" id="new">${state.custom?'New Word':'Next →'}</button></div><div class="message" id="msg">${state.status==='playing'?'You have 6 guesses!':''}</div><div class="board">${rows}</div><div class="keyboard">${keyboard()}</div></section>`);document.querySelector('#back').onclick=()=>state.custom?home():picker(state.theme);document.querySelector('#new').onclick=()=>state.custom?customSetup():start(state.theme,(state.index+1)%30);document.querySelectorAll('[data-key]').forEach(k=>k.onclick=()=>press(k.dataset.key));}
function keyboard(){return ['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'].map((row,i)=>`<div class="keyrow">${i===2?`<button class="key wide" data-key="ENTER">ENTER</button>`:''}${[...row].map(c=>`<button class="key ${state.key[c]||''}" data-key="${c}">${c}</button>`).join('')}${i===2?`<button class="key wide" data-key="BACK">⌫</button>`:''}</div>`).join('')}
function press(k){if(state.status!=='playing')return;if(k==='BACK')state.guess=state.guess.slice(0,-1);else if(k==='ENTER')submit();else if(state.guess.length<state.answer.length)state.guess+=k;renderGame()}
function submit(){if(state.guess.length!==state.answer.length){flash(`Enter ${state.answer.length} letters.`);return}if(!VALID_WORDS.has(state.guess) && state.guess!==state.answer){flash('Not in the word list. Try another word.');return}let a=[...state.answer],g=[...state.guess],result=Array(a.length).fill('absent'),counts={};a.forEach((c,i)=>{if(g[i]===c)result[i]='correct';else counts[c]=(counts[c]||0)+1});g.forEach((c,i)=>{if(result[i]==='correct')return;if(counts[c]>0){result[i]='present';counts[c]--}});state.board.push({letters:state.guess,result});const rank={absent:1,present:2,correct:3};g.forEach((c,i)=>{if(!state.key[c]||rank[result[i]]>rank[state.key[c]])state.key[c]=result[i]});state.row++;let win=state.guess===state.answer;state.guess='';if(win){state.status='won';celebrate();}else if(state.row>=state.max)state.status='lost';if(state.status!=='playing'){setTimeout(()=>{const m=document.querySelector('#msg');if(m)m.textContent=win?'🎉 You got it! Great growing!':`Nice try! The word was ${state.answer}.`;},0)}}
function flash(t){setTimeout(()=>{let m=document.querySelector('#msg');if(m)m.textContent=t},0)}
window.addEventListener('keydown',e=>{if(!state.answer||!document.querySelector('.board'))return;if(e.key==='Enter')press('ENTER');else if(e.key==='Backspace')press('BACK');else if(/^[a-zA-Z]$/.test(e.key))press(e.key.toUpperCase())});home();

let audioCtx;
function celebrationSound(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const now=audioCtx.currentTime;[523.25,659.25,783.99,1046.5].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0.0001,now+i*.11);g.gain.exponentialRampToValueAtTime(.16,now+i*.11+.02);g.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.28);o.connect(g);g.connect(audioCtx.destination);o.start(now+i*.11);o.stop(now+i*.11+.3);});}catch(e){}}
function celebrate(){celebrationSound();const c=document.querySelector('#fireworks'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;c.style.display='block';const particles=[];for(let b=0;b<7;b++){const cx=c.width*(.12+Math.random()*.76),cy=c.height*(.12+Math.random()*.45);for(let i=0;i<38;i++){const a=Math.PI*2*i/38,s=1.5+Math.random()*4;particles.push({x:cx,y:cy,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:70+Math.random()*30,h:(b*52+i*7)%360});}}let frame=0;(function draw(){x.clearRect(0,0,c.width,c.height);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.035;p.life--;x.globalAlpha=Math.max(0,p.life/90);x.fillStyle=`hsl(${p.h} 70% 60%)`;x.beginPath();x.arc(p.x,p.y,3,0,Math.PI*2);x.fill();});x.globalAlpha=1;if(frame++<105)requestAnimationFrame(draw);else c.style.display='none';})();}
